version: '3'

env:
  GOOS: "{{OS}}"

tasks:
  build:
    desc: Build Go Binaries
    cmds:
      - go build -v ./...

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./... -v --timeout 5m

  scan:
    desc: Run security scan
    cmds:
      - gosec -conf .gosec.config.json "./..."

  tools:
    desc: Install tools
    cmds:
      - task: tools:install:golangci-lint
      - task: tools:install:gosec

  tools:install:sops:
    desc: Install sops
    cmds:
      - go install github.com/getsops/sops/v3/cmd/sops@latest

  tools:install:golangci-lint:
    desc: Install golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  tools:install:gosec:
    desc: Install gosec
    cmds:
      - go install github.com/securego/gosec/v2/cmd/gosec@latest

  tools:install:gpg:
    desc: Install gpg
    cmds:
      - task tools:install:gpg:{{OS}}

  tools:install:gpg:windows:
    desc: Install gpg
    cmds:
      - scoop install extras/gpg4win
